const seedDonations = [
  { id: 1, food: 'Fresh vegetable pulao', type: 'Cooked meals', quantity: '40 servings', location: 'Koramangala, Bengaluru', expiry: 'Today, 8:00 PM', quality: 'Excellent', status: 'Available', image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=700&q=80' },
  { id: 2, food: 'Assorted bakery items', type: 'Bakery', quantity: '24 boxes', location: 'Indiranagar, Bengaluru', expiry: 'Tomorrow, 10:00 AM', quality: 'Good', status: 'Matched', image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=700&q=80' },
  { id: 3, food: 'Seasonal fresh produce', type: 'Fruits & vegetables', quantity: '18 kg', location: 'HSR Layout, Bengaluru', expiry: 'Tomorrow, 6:00 PM', quality: 'Excellent', status: 'Available', image: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=700&q=80' },
  { id: 4, food: 'Paneer wraps', type: 'Cooked meals', quantity: '30 servings', location: 'Whitefield, Bengaluru', expiry: 'Today, 9:30 PM', quality: 'Excellent', status: 'Collected', image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=700&q=80' }
];

function getDonations() { return JSON.parse(localStorage.getItem('foodshare_donations') || 'null') || seedDonations; }
function saveDonations(items) { localStorage.setItem('foodshare_donations', JSON.stringify(items)); }
function getUsers() { return JSON.parse(localStorage.getItem('foodshare_users') || 'null') || [{ name: 'Demo Donor', email: 'donor@foodshare.demo', role: 'Donor' }]; }
function esc(value) { return String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char])); }
function statusClass(status) { return status === 'Available' ? '' : status === 'Matched' ? 'orange' : status === 'Delivered' ? 'gray' : ''; }
function showAlert(message) { const el = document.querySelector('.alert'); if (el) { el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 3500); } }
function renderNav() { const page = document.body.dataset.page; const nav = document.querySelector('.site-nav'); if (!nav) return; nav.innerHTML = `<header class="topbar"><div class="container nav"><a class="brand" href="index.html"><span class="brand-mark"><i data-lucide="leaf"></i></span>FoodShare</a><button class="menu-toggle" aria-label="Open navigation"><i data-lucide="menu"></i></button><nav class="nav-links"><a class="${page === 'home' ? 'active' : ''}" href="index.html">Home</a><a class="${page === 'donor' ? 'active' : ''}" href="donor.html">Donate</a><a class="${page === 'recipient' ? 'active' : ''}" href="recipient.html">Find Food</a><a class="${page === 'matching' ? 'active' : ''}" href="matching.html">Smart Match</a><a class="${page === 'tracking' ? 'active' : ''}" href="tracking.html">Tracking</a><a class="${page === 'admin' ? 'active' : ''}" href="admin.html">Admin</a></nav><div class="nav-actions"><a class="btn btn-ghost" href="login.html">Log in</a><a class="btn btn-primary" href="register.html">Join FoodShare</a></div></div></header>`; document.querySelector('.menu-toggle').addEventListener('click', () => document.querySelector('.nav-links').classList.toggle('open')); if (window.lucide) lucide.createIcons(); }
function donationRow(item) { return `<tr><td><strong>${esc(item.food)}</strong><br><small>${esc(item.type)}</small></td><td>${esc(item.quantity)}</td><td>${esc(item.location)}</td><td>${esc(item.expiry)}</td><td><span class="status ${statusClass(item.status)}">${esc(item.status)}</span></td></tr>`; }
function foodCard(item) { return `<article class="food-card reveal"><div class="food-image" style="background-image:url('${item.image}')"></div><div class="food-info"><h3>${esc(item.food)}</h3><div class="food-meta"><span><i data-lucide="package"></i>${esc(item.quantity)}</span><span><i data-lucide="map-pin"></i>${esc(item.location)}</span><span><i data-lucide="clock-3"></i>Expires ${esc(item.expiry)}</span></div><div class="score"><span>${esc(item.status)} for request</span><strong>${item.status === 'Available' ? '95%' : '88%'}</strong></div><button class="btn btn-primary request-btn" data-id="${item.id}" style="width:100%;margin-top:12px">Request Food <i data-lucide="arrow-up-right"></i></button></div></article>`; }
function initHome() { const stats = document.querySelectorAll('[data-stat]'); if (stats.length) { const items = getDonations(); const values = { donations: items.length + 38, meals: '1,284', partners: '26' }; stats.forEach(el => el.textContent = values[el.dataset.stat]); } }
function initDonor() { const body = document.querySelector('#donationRows'); if (body) body.innerHTML = getDonations().slice().reverse().map(donationRow).join(''); const form = document.querySelector('#donationForm'); if (form) form.addEventListener('submit', event => { event.preventDefault(); const data = Object.fromEntries(new FormData(form)); const items = getDonations(); items.push({ id: Date.now(), food: data.food, type: data.type, quantity: data.quantity, location: data.location, expiry: data.expiry, quality: data.quality, status: 'Available', image: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=700&q=80' }); saveDonations(items); body.innerHTML = items.slice().reverse().map(donationRow).join(''); form.reset(); showAlert('Donation published. Matching recipients are being found.'); }); }
function initRecipient() { const grid = document.querySelector('#foodGrid'); if (!grid) return; const available = getDonations().filter(item => item.status === 'Available'); grid.innerHTML = available.map(foodCard).join(''); if (window.lucide) lucide.createIcons(); grid.querySelectorAll('.request-btn').forEach(btn => btn.addEventListener('click', () => { const items = getDonations(); const item = items.find(donation => donation.id === Number(btn.dataset.id)); if (item) { item.status = 'Matched'; saveDonations(items); btn.textContent = 'Request sent'; btn.classList.replace('btn-primary', 'btn-light'); btn.disabled = true; showAlert(`Request sent for ${item.food}. The donor will be notified.`); } })); }
function initMatching() { const items = getDonations(); const list = document.querySelector('#matchList'); if (list) list.innerHTML = items.slice(0, 4).map((item, index) => `<div class="match-item"><div class="match-avatar">${['NG', 'SH', 'CF', 'HS'][index]}</div><div class="match-main"><strong>${esc(item.food)}</strong><small>${esc(item.location)} · ${esc(item.quantity)}</small><div class="progress" style="margin-top:8px"><span style="width:${95-index*4}%"></span></div></div><div class="match-score">${95-index*4}%</div></div>`).join(''); }
function initAdmin() { const items = getDonations(); const cells = { adminDonations: items.length + 38, adminAvailable: items.filter(x => x.status === 'Available').length + 17, adminDelivered: 34, adminDonors: 142, adminRecipients: 86 }; Object.entries(cells).forEach(([id, value]) => { const el = document.getElementById(id); if (el) el.textContent = value; }); }
function initAuth() { const form = document.querySelector('#authForm'); if (!form) return; form.addEventListener('submit', event => { event.preventDefault(); const data = Object.fromEntries(new FormData(form)); if (document.body.dataset.page === 'register') { const users = getUsers(); users.push({ name: data.name, email: data.email, role: data.role }); localStorage.setItem('foodshare_users', JSON.stringify(users)); showAlert('Account created. Welcome to FoodShare.'); setTimeout(() => window.location.href = data.role === 'Recipient' ? 'recipient.html' : data.role === 'Admin' ? 'admin.html' : 'donor.html', 600); } else { showAlert('Welcome back. Redirecting to your dashboard.'); setTimeout(() => window.location.href = 'donor.html', 600); } }); }
document.addEventListener('DOMContentLoaded', () => { renderNav(); initHome(); initDonor(); initRecipient(); initMatching(); initAdmin(); initAuth(); if (window.lucide) lucide.createIcons(); });
